name: Karate API Tests

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  karate-tests:
    runs-on: ubuntu-latest # Uses a hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Java (JDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin distribution
          java-version: '11'

      # Step 3: Cache Maven dependencies (optional but speeds up builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: mvn clean install -DskipTests

      # Step 5: Run the Karate tests using your custom runner class
      - name: Execute Karate Runner
        run: mvn test -Dtest=mainrunner

      # Step 6: Upload Test Reports
      - name: Upload Karate Reports
        uses: actions/upload-artifact@v3
        with:
          name: karate-reports
          path: target/karate-reports/
